CREATE TABLE Tenant (
    Id UUID PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE "User" (
    Id UUID PRIMARY KEY,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Tel TEXT,
    Role TEXT NOT NULL, 
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_user_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE
);

CREATE TABLE Sport (
    Id UUID PRIMARY KEY,
    Name TEXT NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_sport_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE
);

CREATE TABLE Coach_Sports (
    Id UUID PRIMARY KEY,
    CoachId UUID NOT NULL,
    SportId UUID NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_coachsports_coach
        FOREIGN KEY (CoachId)
        REFERENCES "User"(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_coachsports_sport
        FOREIGN KEY (SportId)
        REFERENCES Sport(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_coachsports_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE,
    CONSTRAINT uc_coach_sport UNIQUE (CoachId, SportId)
);

CREATE TABLE Session (
    Id UUID PRIMARY KEY,
    CoachId UUID NOT NULL,
    SportId UUID NOT NULL,
    Fee NUMERIC(10, 2) NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_session_coach
        FOREIGN KEY (CoachId)
        REFERENCES "User"(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_session_sport
        FOREIGN KEY (SportId)
        REFERENCES Sport(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_session_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE
);

CREATE TABLE Athlete (
    Id UUID PRIMARY KEY,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    Tel TEXT,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_athlete_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE
);

CREATE TABLE Athlete_Enrollments (
    Id UUID PRIMARY KEY,
    CoachId UUID NOT NULL,
    SportId UUID NOT NULL,
    AthleteId UUID NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_enrollments_coach
        FOREIGN KEY (CoachId)
        REFERENCES "User"(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_sport
        FOREIGN KEY (SportId)
        REFERENCES Sport(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_athlete
        FOREIGN KEY (AthleteId)
        REFERENCES Athlete(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_enrollments_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE,
    CONSTRAINT uc_athlete_enrollment UNIQUE (CoachId, SportId, AthleteId)
);

CREATE TABLE Payment (
    Id UUID PRIMARY KEY,
    SessionId UUID NOT NULL, 
    AthleteEnrollmentId UUID NOT NULL,
    ExpiresAt DATE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TenantId UUID NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_payment_session
        FOREIGN KEY (SessionId)
        REFERENCES Session(Id)
        ON DELETE CASCADE, 
    CONSTRAINT fk_payment_enrollment
        FOREIGN KEY (AthleteEnrollmentId)
        REFERENCES Athlete_Enrollments(Id)
        ON DELETE CASCADE,
    CONSTRAINT fk_payment_tenant
        FOREIGN KEY (TenantId)
        REFERENCES Tenant(Id)
        ON DELETE CASCADE
);