services:
  sportdesk_db:
    image: postgres:16-alpine
    container_name: sportdesk_postgres
    restart: always
    environment:
      POSTGRES_USER: sportdesk
      POSTGRES_PASSWORD: shumsekret
      POSTGRES_DB: sportdesk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: